# Generated by Django 3.0.10 on 2020-10-01 13:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Event timestamp')),
            ],
        ),
    ]
